from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum


class RecoveryClassification(StrEnum):
    TRANSIENT = "TRANSIENT"
    REPAIRABLE = "REPAIRABLE"
    MANUAL_ONLY = "MANUAL_ONLY"


class ReleasePolicy(StrEnum):
    AUTO_WHEN_CLEAN = "AUTO_WHEN_CLEAN"
    AUTO_AFTER_REPAIR_AND_VERIFICATION = "AUTO_AFTER_REPAIR_AND_VERIFICATION"
    MANUAL_ONLY = "MANUAL_ONLY"


class PauseState(StrEnum):
    TRADING = "TRADING"
    PAUSED_RECOVERING = "PAUSED_RECOVERING"
    PAUSED_WAITING_STABILITY = "PAUSED_WAITING_STABILITY"
    PAUSED_MANUAL_ONLY = "PAUSED_MANUAL_ONLY"


class SafetyTier(StrEnum):
    TRANSIENT_GLOBAL_BLOCK = "TRANSIENT_GLOBAL_BLOCK"
    SCOPED_QUARANTINE = "SCOPED_QUARANTINE"
    GLOBAL_MANUAL_HARD_STOP = "GLOBAL_MANUAL_HARD_STOP"


class IncidentScope(StrEnum):
    POSITION = "POSITION"
    TOKEN = "TOKEN"
    EVENT = "EVENT"
    ACCOUNT = "ACCOUNT"
    GLOBAL = "GLOBAL"
    UNKNOWN = "UNKNOWN"


UNKNOWN_OBSERVATION_WINDOW_SECONDS = 60.0


@dataclass(frozen=True)
class RecoveryPolicy:
    classification: RecoveryClassification
    release_policy: ReleasePolicy
    required_evidence: tuple[str, ...]
    remediation: str
    safety_tier: SafetyTier


def _transient(remediation: str, *evidence: str) -> RecoveryPolicy:
    return RecoveryPolicy(
        RecoveryClassification.TRANSIENT,
        ReleasePolicy.AUTO_WHEN_CLEAN,
        tuple(evidence),
        remediation,
        SafetyTier.TRANSIENT_GLOBAL_BLOCK,
    )


def _repairable(remediation: str, *evidence: str) -> RecoveryPolicy:
    return RecoveryPolicy(
        RecoveryClassification.REPAIRABLE,
        ReleasePolicy.AUTO_AFTER_REPAIR_AND_VERIFICATION,
        tuple(evidence),
        remediation,
        SafetyTier.TRANSIENT_GLOBAL_BLOCK,
    )


def _manual(remediation: str, *evidence: str) -> RecoveryPolicy:
    return RecoveryPolicy(
        RecoveryClassification.MANUAL_ONLY,
        ReleasePolicy.MANUAL_ONLY,
        tuple(evidence),
        remediation,
        SafetyTier.GLOBAL_MANUAL_HARD_STOP,
    )


RECOVERY_POLICIES: dict[str, RecoveryPolicy] = {
    "MARKET_WS_DOWN": _transient("MARKET_WS_RECONNECT", "MARKET_WS_FRESH"),
    "MARKET_DATA_NOT_READY": _transient(
        "MARKET_WS_VERIFY_OR_RECONNECT", "MARKET_BOOKS_FRESH"
    ),
    "RECONNECT_AWAITING_FRESH_BOOKS": _transient(
        "WAIT_FOR_FRESH_BOOKS", "MARKET_BOOKS_FRESH"
    ),
    "RECONNECT_RECONCILIATION_PENDING": _transient(
        "WAIT_FOR_RECONNECT_RECONCILIATION", "RECONCILIATION_CLEAN"
    ),
    "MARKET_WS_INGRESS_QUEUE_SATURATED": _transient(
        "MARKET_WS_RESUBSCRIBE", "MARKET_BOOKS_FRESH"
    ),
    "INGRESS_QUEUE_SATURATED_RESYNC": _transient(
        "MARKET_WS_RESUBSCRIBE", "MARKET_BOOKS_FRESH"
    ),
    "MARKET_METADATA_CACHE_MISS": _transient(
        "MARKET_DISCOVERY_REFRESH", "MARKET_BOOKS_FRESH"
    ),
    "PERSISTENCE_EXECUTOR_UNAVAILABLE": _transient(
        "RETRY_MARKET_PERSISTENCE", "MARKET_BOOKS_FRESH"
    ),
    "USER_WS_DOWN": _transient(
        "USER_WS_RECONNECT_AND_RECONCILE", "USER_WS_FRESH", "RECONCILIATION_CLEAN"
    ),
    "USER_WS_STALE": _transient(
        "USER_WS_RECONNECT_AND_RECONCILE", "USER_WS_FRESH", "RECONCILIATION_CLEAN"
    ),
    "MARKET_DATA_STALE": _transient("MARKET_WS_VERIFY_OR_RECONNECT", "MARKET_BOOKS_FRESH"),
    "STALE_EXCHANGE_TIMESTAMP": _transient(
        "MARKET_WS_VERIFY_OR_RECONNECT", "MARKET_BOOKS_FRESH"
    ),
    "FUTURE_EXCHANGE_TIMESTAMP": _transient(
        "MARKET_WS_VERIFY_OR_RECONNECT", "MARKET_BOOKS_FRESH"
    ),
    "BOOK_NOT_READY": _transient("MARKET_WS_RESUBSCRIBE", "MARKET_BOOKS_FRESH"),
    "MARKET_WS_NOT_CONNECTED": _transient("MARKET_WS_RECONNECT", "MARKET_WS_FRESH"),
    "WS_DISCONNECTED": _transient("MARKET_WS_RECONNECT", "MARKET_WS_FRESH"),
    "EVENT_NOT_SUBSCRIBED": _transient("MARKET_WS_RESUBSCRIBE", "MARKET_BOOKS_FRESH"),
    "UNKNOWN_EVENT": _transient("MARKET_DISCOVERY_REFRESH", "MARKET_BOOKS_FRESH"),
    "BEST_PRICE_PENDING_DEPTH": _transient("MARKET_WS_RESUBSCRIBE", "MARKET_BOOKS_FRESH"),
    "FRAME_SUPERSEDED": _transient("WAIT_FOR_CURRENT_FRAME", "MARKET_BOOKS_FRESH"),
    "BEST_PRICE_MISMATCH": _transient("MARKET_WS_RESUBSCRIBE", "MARKET_BOOKS_FRESH"),
    "DELTA_BEFORE_SNAPSHOT": _transient("MARKET_WS_RESUBSCRIBE", "MARKET_BOOKS_FRESH"),
    "BEST_UPDATE_BEFORE_SNAPSHOT": _transient("MARKET_WS_RESUBSCRIBE", "MARKET_BOOKS_FRESH"),
    "MALFORMED_DELTA": _transient("MARKET_WS_RESUBSCRIBE", "MARKET_BOOKS_FRESH"),
    "OUT_OF_ORDER_EXCHANGE_TIMESTAMP": _transient(
        "WAIT_FOR_CURRENT_FRAME", "MARKET_BOOKS_FRESH"
    ),
    "STALE_CONNECTION_GENERATION": _transient(
        "WAIT_FOR_CURRENT_CONNECTION", "MARKET_WS_FRESH"
    ),
    "FRESHNESS_PROVIDER_UNAVAILABLE": _transient(
        "MARKET_WS_VERIFY_OR_RECONNECT", "MARKET_BOOKS_FRESH"
    ),
    "HEARTBEAT_FAILURE": _transient(
        "RETRY_ORDER_HEARTBEAT", "HEARTBEAT_SUCCESS_AFTER_ACQUISITION"
    ),
    "GEOGRAPHIC_EVIDENCE_STALE": _transient(
        "REFRESH_GEOGRAPHIC_PREFLIGHT", "GEOGRAPHIC_ALLOWED_FRESH"
    ),
    "RECOVERY_MONITOR_TEMPORARY_ERROR": _transient(
        "RETRY_RECOVERY_ENGINE", "RECOVERY_ENGINE_HEALTHY"
    ),
    "SAFETY_STARTUP_HOLD": _transient(
        "INITIALIZE_AND_VERIFY", "STARTUP_READINESS_COMPLETE"
    ),
    "STARTUP_RECONCILIATION_REQUIRED": _transient(
        "RUN_RECONCILIATION", "RECONCILIATION_CLEAN"
    ),
    "RECONCILIATION_RATE_LIMITED": _transient(
        "RETRY_RECONCILIATION_WITH_BACKOFF", "RECONCILIATION_CLEAN_AFTER_ACQUISITION"
    ),
    "RECONCILIATION_TEMPORARY_ERROR": _transient(
        "RETRY_RECONCILIATION_WITH_BACKOFF", "RECONCILIATION_CLEAN_AFTER_ACQUISITION"
    ),
    "RECONCILIATION_GAP": _repairable(
        "RECONCILE_REPAIR_VERIFY", "RECONCILIATION_CLEAN_AFTER_ACQUISITION"
    ),
    "USER_WS_QUEUE_LOSS": _repairable(
        "RECONCILE_PRIVATE_STATE", "RECONCILIATION_CLEAN_AFTER_ACQUISITION"
    ),
    "USER_WS_PERSISTENCE_UNCERTAIN": _repairable(
        "RECONCILE_PRIVATE_STATE", "RECONCILIATION_CLEAN_AFTER_ACQUISITION"
    ),
    "EXIT_RECONCILIATION_REQUIRED": _repairable(
        "RECONCILE_EXECUTION_STATE", "RECONCILIATION_CLEAN_AFTER_ACQUISITION"
    ),
    "CANCEL_UNCERTAIN": _repairable(
        "RECONCILE_ORDER_STATE", "RECONCILIATION_CLEAN_AFTER_ACQUISITION"
    ),
    "ACTIVE_EXIT_REMOTE_ORDER_ID_UNKNOWN": _repairable(
        "RECONCILE_ORDER_STATE", "RECONCILIATION_CLEAN_AFTER_ACQUISITION"
    ),
    "TP_REMOTE_ORDER_ID_UNKNOWN": _repairable(
        "RECONCILE_ORDER_STATE", "RECONCILIATION_CLEAN_AFTER_ACQUISITION"
    ),
    "STOP_CANCEL_UNCERTAIN": _repairable(
        "RECONCILE_ORDER_STATE", "RECONCILIATION_CLEAN_AFTER_ACQUISITION"
    ),
    "STOP_EXIT_PRICE_PROTECTION_EXHAUSTED": _repairable(
        "FLATTEN_LATCHED_POSITION", "LATCHED_POSITION_FLAT"
    ),
    "OPERATOR_PAUSE": _manual("OPERATOR_REVIEW"),
    "KILL_SWITCH_ACTIVE": _manual("OPERATOR_REVIEW_KILL_SWITCH"),
    "CANARY_NOT_ARMED": _manual("OPERATOR_ARM_CANARY"),
    "STRATEGY_NOT_READY": _transient(
        "WAIT_FOR_STRATEGY_READINESS", "STRATEGY_READY"
    ),
    "MARKET_SCOPE_MISMATCH": _manual("OPERATOR_REVIEW_MARKET_SCOPE"),
    "MISSING_DYNAMIC_MARKET_CONSTRAINTS": _manual("OPERATOR_REVIEW_MARKET_CONSTRAINTS"),
    "STRATEGY_PROCESSING_FAILED": _manual("OPERATOR_REVIEW_INTERNAL_FAILURE"),
    "OPERATOR_MAINTENANCE_HOLD": _manual("OPERATOR_REVIEW"),
    "CONFIGURED_STARTUP_PAUSE": _manual("OPERATOR_REVIEW"),
    "EMERGENCY_CLOSE_REQUESTED": _manual("OPERATOR_REVIEW"),
    "DAILY_LOSS_LIMIT": _manual("OPERATOR_RISK_REVIEW"),
    "CONSECUTIVE_FAILED_ORDERS": _manual("OPERATOR_RISK_REVIEW"),
    "CONSECUTIVE_LOSING_DEALS": _manual("OPERATOR_RISK_REVIEW"),
    "CONFIG_INVALID": _manual("FIX_CONFIGURATION"),
    "PROVENANCE_UNVERIFIED": _manual("OPERATOR_DEPLOYMENT_ATTESTATION"),
    "GEOGRAPHIC_AVAILABILITY_FAILED": _manual("OPERATOR_COMPLIANCE_REVIEW"),
    "RECONCILIATION_FAILED": _manual("OPERATOR_FINANCIAL_REVIEW"),
    "RECONCILIATION_CONTRADICTION": _manual(
        "OPERATOR_FINANCIAL_REVIEW", "AUTHORITATIVE_CONTRADICTION_RESOLVED"
    ),
}


GLOBAL_HARD_STOP_REASONS = frozenset({
    "OPERATOR_PAUSE",
    "KILL_SWITCH_ACTIVE",
    "CONFIG_INVALID",
    "PROVENANCE_UNVERIFIED",
    "GEOGRAPHIC_AVAILABILITY_FAILED",
    "DAILY_LOSS_LIMIT",
    "EMERGENCY_CLOSE_REQUESTED",
})

UNKNOWN_POLICY = _transient(
    "CLASSIFY_UNKNOWN_CAUSE", "CAUSE_CLASSIFICATION_REQUIRED"
)
UNKNOWN_ESCALATED_POLICY = _manual(
    "OPERATOR_REVIEW_UNKNOWN_CAUSE", "CAUSE_CLASSIFICATION_REQUIRED"
)
SCOPED_UNKNOWN_POLICY = RecoveryPolicy(
    RecoveryClassification.REPAIRABLE,
    ReleasePolicy.AUTO_AFTER_REPAIR_AND_VERIFICATION,
    ("SCOPED_QUARANTINE_RECORDED", "RECONCILIATION_CLEAN"),
    "QUARANTINE_AND_VERIFY",
    SafetyTier.SCOPED_QUARANTINE,
)


def is_known_reason(reason: str) -> bool:
    return str(reason or "").upper() in RECOVERY_POLICIES


def recovery_policy(
    reason: str,
    *,
    unknown_age_seconds: float = 0.0,
    incident_scope: str = IncidentScope.UNKNOWN,
) -> RecoveryPolicy:
    normalized = str(reason or "").upper()
    known = RECOVERY_POLICIES.get(normalized)
    if known is not None:
        return known
    scope = str(incident_scope or IncidentScope.UNKNOWN).upper()
    if scope in {
        IncidentScope.POSITION,
        IncidentScope.TOKEN,
        IncidentScope.EVENT,
    }:
        return SCOPED_UNKNOWN_POLICY
    if float(unknown_age_seconds) >= UNKNOWN_OBSERVATION_WINDOW_SECONDS:
        return UNKNOWN_ESCALATED_POLICY
    return UNKNOWN_POLICY
